kafka.bootstrap.servers=localhost:9092
kafka.topic.input=Employeefinal
kafka.topic.high_salary=high_salary
kafka.topic.low_salary=low_salary

mysql.url=jdbc:mysql://localhost:3306/EmployeeTest
mysql.user=root
mysql.password=${MYSQL_PASSWORD}
mysql.driver=com.mysql.cj.jdbc.Driver

checkpoint.base.dir=/tmp/checkpoints